name: Python CI

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the workflow

jobs:
  build:
    runs-on: self-hosted  # Indicates that a self-hosted runner is being used

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Replace with the Python version you need
        architecture: x64  # Add this line for 64-bit Python if needed

    - name: Install Jupyter
      run: |
        python -m pip install --upgrade pip
        pip install jupyter

    - name: Run Python script
      run: |
        jupyter nbconvert --execute Calc.ipynb